[package]
name = "aoc2019"
version = "0.1.0"
authors = ["BlockCat <zinoonomiwo@gmail.com>"]
edition = "2018"
rustflags = ["-C target-cpu=native"]

[dependencies]
itertools = "0.8.2"
hashbrown = "0.6.3"
bitvec = "0.16.0"

[lib]
name = "utils"
path = "src/lib.rs"
